### ISSUE TITLE
next-auth supabase permission bug

### ISSUE THREAD

**Issue by thiras** [depremguvenligi/binabilgi#48]
```
[next-auth][error][adapter_error_getUserByAccount] 
https://next-auth.js.org/errors#adapter_error_getuserbyaccount permission denied for schema next_auth {
  code: '42501',
  details: null,
  hint: null,
  message: 'permission denied for schema next_auth'
}
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
https://next-auth.js.org/errors#oauth_callback_handler_error permission denied for schema next_auth UnknownError [GetUserByAccountError]: permission denied for schema next_auth
    at _callee2$ (/home/thiras/HDD/dev/depremguvenligi/binabilgi/node_modules/next-auth/core/errors.js:374:19)
    at tryCatch (/home/thiras/HDD/dev/depremguvenligi/binabilgi/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/home/thiras/HDD/dev/depremguvenligi/binabilgi/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.throw (/home/thiras/HDD/dev/depremguvenligi/binabilgi/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (/home/thiras/HDD/dev/depremguvenligi/binabilgi/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _throw (/home/thiras/HDD/dev/depremguvenligi/binabilgi/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: '42501'
}
```

Related; https://stackoverflow.com/questions/67551593/supabase-client-permission-denied-for-schema-public

**Comment by thiras** [comment]
Fixed by refactoring migrations through Supabase studio
